load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["listener.go"],
    importpath = "aqwari.net/net/styx/internal/netutil",
    visibility = ["//aqwari.net/net/styx:__subpackages__"],
)
